export const features = [
  {
    key: "blog",
    title: "Blog",
    type: "object_type",
    emoji: "📝",
    description: `Adds a Blog Object type to your Project. Blog fields include:`,
    field_list: [
      "Hero image",
      "Content in Markdown",
      "Author single Object relationship Metafield",
      "Categories multiple Object relationship Metafield",
      "SEO fields (see below)",
    ],
    confirmation: `This will install the following Object types: \`blog-posts\`,\`authors\`, and \`categories\` as well as demo content.`,
    preview_link: "/features/blog",
    screenshot:
      "https://imgix.cosmicjs.com/36a6ee10-62e0-11ee-b975-cb0cfadd93ad-blog.png",
  },
  {
    key: "pages",
    title: "Pages",
    type: "object_type",
    emoji: "📄",
    description: `Adds a Pages Object type to your Bucket. Fields include:`,
    field_list: [
      "Hero image",
      "Rich text content",
      "Repeating layouts in: 1 column and alternating 2 columns with headline, image, and rich text content.",
      "SEO fields (see below)",
    ],
    confirmation: `This will install a \`pages\` Object type to your Bucket as well as demo content.`,
    preview_link: "/features/page",
    screenshot:
      "https://imgix.cosmicjs.com/f3029020-6af4-11ee-b27c-e13e14dddc51-pages.png",
  },
  {
    key: "navigation_menus",
    title: "Navigation Menus",
    type: "object_type",
    emoji: "🖱",
    description: `Adds Navigation Menus Object type to your Bucket. Fields include:`,
    field_list: [
      "Links repeater with title, link, and option to open in a new browser tab",
    ],
    confirmation: `This will install a \`navigation-menus\` Object type to your Bucket as well as demo content.`,
    preview_link: "/features/nav-menus",
    screenshot:
      "https://imgix.cosmicjs.com/07a8df20-6889-11ee-b27c-e13e14dddc51-nav-menus.png",
  },
  {
    key: "global_settings",
    title: "Global Settings",
    type: "object_type",
    emoji: "⚙️",
    description: `Adds Global Settings Object type to your Bucket. Fields include:`,
    field_list: [
      "Company name",
      "Logo image",
      "Contact email",
      "Phone number",
      "Repeater Metafield with fields for social links: title, URL, and logo.",
    ],
    confirmation: `This will install a \`global-settings\` Object type to your Bucket as well as demo content.`,
    preview_link: "/features/settings",
    screenshot:
      "https://imgix.cosmicjs.com/55082f80-6bb0-11ee-b27c-e13e14dddc51-global-settings.png",
  },
  {
    key: "faqs",
    title: "FAQs",
    type: "metafields",
    emoji: "❓",
    description: `Adds an FAQs feature to any existing Object type.`,
    field_list: ["Question", "Answer"],
    confirmation: `This will add a new Metafield with key \`faqs\` to the selected Object types.`,
    preview_link: "/features/faqs",
    screenshot:
      "https://imgix.cosmicjs.com/4e388d20-6bac-11ee-b27c-e13e14dddc51-faqs.png",
  },
  {
    key: "products",
    title: "Products",
    type: "object_type",
    emoji: "🛍️",
    description: `Adds a Products Object type to your Bucket. Fields include:`,
    field_list: [
      "Image",
      "Image gallery with repeating image and description",
      "Price",
      "Quantity",
      "Description",
      "SEO fields (see below)",
    ],
    confirmation: `This will install a \`products\` Object type to your Bucket as well as demo content.`,
  },
  {
    key: "seo",
    title: "SEO fields",
    type: "metafields",
    emoji: "🔍",
    description: `Adds SEO fields to any existing Object type. Fields include:`,
    field_list: [
      "SEO Title",
      "SEO Description",
      "OG title",
      "OG description",
      "OG image",
    ],
    confirmation: `This will add a new Metafield with key \`seo\` to the selected Object types.`,
  },
]
