export const features = [
  {
    key: "blog",
    title: "Blog",
    type: "object_type",
    emoji: "📝",
    description: `Adds a Blog Posts Object type to your Project. Blog fields include:`,
    field_list: [
      "Hero image",
      "Content in Markdown",
      "Author single Object relationship Metafield",
      "Categories multiple Object relationship Metafield",
      "SEO fields (see below)",
    ],
    confirmation: `This will install the following Object types: \`blog-posts\`,\`authors\`, and \`categories\` as well as demo content.`,
    preview_link: "/features/blog",
  },
  {
    key: "pages",
    title: "Pages",
    type: "object_type",
    emoji: "📄",
    description: `Adds a Pages Object type to your Bucket. Fields include:`,
    field_list: [
      "Hero image",
      "Rich text content",
      "Repeating layouts in: 1 column and alternating 2 columns with headline, image, and rich text content.",
      "SEO fields (see below)",
    ],
    confirmation: `This will install a \`pages\` Object type to your Bucket as well as demo content.`,
    preview_link: "/features/page",
  },
  {
    key: "products",
    title: "Products",
    type: "object_type",
    emoji: "🛍️",
    description: `Adds a Products Object type to your Bucket. Fields include:`,
    field_list: [
      "Image",
      "Image gallery with repeating image and description",
      "Price",
      "Quantity",
      "Description",
      "SEO fields (see below)",
    ],
    confirmation: `This will install a \`products\` Object type to your Bucket as well as demo content.`,
  },
  {
    key: "navigation_menus",
    title: "Navigation Menus",
    type: "object_type",
    emoji: "🖱",
    description: `Adds Navigation Menus Object type to your Bucket. Fields include:`,
    field_list: ["Links repeater with title and URL"],
    confirmation: `This will install a \`navigation-menus\` Object type to your Bucket as well as demo content.`,
  },
  {
    key: "global_settings",
    title: "Global Settings",
    type: "object_type",
    emoji: "⚙️",
    description: `Adds Global Settings Object type to your Bucket. Fields include:`,
    field_list: [
      "Company name",
      "Logo image",
      "Contact email",
      "Repeater Metafield with fields for social links: title, URL, and logo.",
    ],
    confirmation: `This will install a \`settings\` Object type to your Bucket as well as demo content.`,
  },
  {
    key: "seo",
    title: "SEO fields",
    type: "metafields",
    emoji: "🔍",
    description: `Adds SEO fields to any existing Object type. Fields include:`,
    field_list: [
      "SEO Title",
      "SEO Description",
      "OG title",
      "OG description",
      "OG image",
    ],
    confirmation: `This will add a new Metafield with key \`seo\` to the selected Object types.`,
  },
  {
    key: "faqs",
    title: "FAQs",
    type: "metafields",
    emoji: "❓",
    description: `Adds an FAQs feature to any existing Object type.`,
    field_list: ["Question", "Answer"],
    confirmation: `This will add a new Metafield with key \`faqs\` to the selected Object types.`,
  },
]
